// app/home/_components/video-grid.tsx
import React from 'react'
import VideoCard from './VideoCard'

export interface Video {
  id: string
  title: string
  thumbnail: string
  duration: string
  views: string
  category: string
  description: string
  releaseDate: string
  rating: number // out of 5
  ageRating: string // "PG", "PG-13", "R", "TV-MA", etc.
  director?: string
  cast?: string[]
  tags: string[]
  isNew?: boolean
  isTrending?: boolean
  isFeatured?: boolean
  videoUrl?: string // for future video playback
  trailerUrl?: string
}

const VideoGrid = () => {
  const videos: Video[] = [
    {
      id: "vid_001_stranger_things_s4",
      title: "Stranger Things: Season 4",
      thumbnail: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=80",
      duration: "2h 15m",
      views: "12.5M",
      category: "Sci-Fi Thriller",
      description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
      releaseDate: "2024-05-27",
      rating: 4.7,
      ageRating: "TV-14",
      director: "The Duffer Brothers",
      cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"],
      tags: ["sci-fi", "thriller", "supernatural", "80s"],
      isNew: true,
      isTrending: true,
      isFeatured: true,
      videoUrl: "/videos/stranger-things-s4.mp4",
      trailerUrl: "/trailers/stranger-things-s4.mp4"
    },
    {
      id: "vid_002_the_crown_final",
      title: "The Crown: Final Season",
      thumbnail: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80",
      duration: "1h 45m",
      views: "8.3M",
      category: "Historical Drama",
      description: "The final chapter of Queen Elizabeth II's reign, exploring the royal family's journey through the late 20th century.",
      releaseDate: "2024-11-16",
      rating: 4.5,
      ageRating: "TV-MA",
      director: "Peter Morgan",
      cast: ["Imelda Staunton", "Jonathan Pryce", "Lesley Manville"],
      tags: ["historical", "drama", "royal", "british"],
      isNew: false,
      isTrending: false,
      isFeatured: true
    },
    {
      id: "vid_003_breaking_bad_complete",
      title: "Breaking Bad: Complete Series",
      thumbnail: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800&q=80",
      duration: "3h 20m",
      views: "45.2M",
      category: "Crime Drama",
      description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.",
      releaseDate: "2008-01-20",
      rating: 4.9,
      ageRating: "TV-MA",
      director: "Vince Gilligan",
      cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
      tags: ["crime", "drama", "thriller", "drugs"],
      isNew: false,
      isTrending: true,
      isFeatured: true
    },
    {
      id: "vid_004_wednesday",
      title: "Wednesday",
      thumbnail: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80",
      duration: "1h 30m",
      views: "23.7M",
      category: "Mystery Comedy",
      description: "Wednesday Addams' years as a student at Nevermore Academy, attempting to master her emerging psychic ability.",
      releaseDate: "2022-11-23",
      rating: 4.3,
      ageRating: "TV-14",
      director: "Tim Burton",
      cast: ["Jenna Ortega", "Gwendoline Christie", "Catherine Zeta-Jones"],
      tags: ["mystery", "comedy", "supernatural", "teen"],
      isNew: true,
      isTrending: true,
      isFeatured: false
    },
    {
      id: "vid_005_last_of_us",
      title: "The Last of Us",
      thumbnail: "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=800&q=80",
      duration: "2h 05m",
      views: "34.1M",
      category: "Post-Apocalyptic",
      description: "Twenty years after a fungal outbreak ravages the planet, survivors Joel and Ellie embark on a brutal journey across America.",
      releaseDate: "2023-01-15",
      rating: 4.8,
      ageRating: "TV-MA",
      director: "Craig Mazin",
      cast: ["Pedro Pascal", "Bella Ramsey", "Anna Torv"],
      tags: ["post-apocalyptic", "drama", "zombie", "adventure"],
      isNew: true,
      isTrending: true,
      isFeatured: true
    },
    {
      id: "vid_006_dark",
      title: "Dark",
      thumbnail: "https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&q=80",
      duration: "1h 55m",
      views: "19.8M",
      category: "Mystery Sci-Fi",
      description: "A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations.",
      releaseDate: "2017-12-01",
      rating: 4.6,
      ageRating: "TV-MA",
      director: "Baran bo Odar",
      cast: ["Louis Hofmann", "Lisa Vicari", "Maja Schöne"],
      tags: ["mystery", "sci-fi", "time-travel", "german"],
      isNew: false,
      isTrending: false,
      isFeatured: false
    },
    {
      id: "vid_007_peaky_blinders",
      title: "Peaky Blinders",
      thumbnail: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=800&q=80",
      duration: "2h 30m",
      views: "28.5M",
      category: "Period Crime",
      description: "A notorious gang in 1919 Birmingham, England, is led by the fierce Tommy Shelby, a crime boss set on moving up in the world.",
      releaseDate: "2013-09-12",
      rating: 4.7,
      ageRating: "TV-MA",
      director: "Steven Knight",
      cast: ["Cillian Murphy", "Paul Anderson", "Helen McCrory"],
      tags: ["crime", "period", "gangster", "british"],
      isNew: false,
      isTrending: true,
      isFeatured: false
    },
    {
      id: "vid_008_the_witcher",
      title: "The Witcher",
      thumbnail: "https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=800&q=80",
      duration: "1h 50m",
      views: "41.2M",
      category: "Fantasy Adventure",
      description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
      releaseDate: "2019-12-20",
      rating: 4.4,
      ageRating: "TV-MA",
      director: "Lauren Schmidt Hissrich",
      cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan"],
      tags: ["fantasy", "adventure", "magic", "medieval"],
      isNew: true,
      isTrending: true,
      isFeatured: true
    },
    {
      id: "vid_009_planet_earth_iii",
      title: "Planet Earth III",
      thumbnail: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80",
      duration: "55m",
      views: "67.3M",
      category: "Nature Documentary",
      description: "Discover the extraordinary ways animals meet the challenges of surviving in the most iconic habitats on earth.",
      releaseDate: "2023-10-22",
      rating: 4.9,
      ageRating: "TV-G",
      director: "David Attenborough",
      tags: ["documentary", "nature", "wildlife", "educational"],
      isNew: true,
      isTrending: true,
      isFeatured: true
    },
    {
      id: "vid_010_mandalorian",
      title: "The Mandalorian",
      thumbnail: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?w=800&q=80",
      duration: "45m",
      views: "89.4M",
      category: "Space Western",
      description: "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
      releaseDate: "2019-11-12",
      rating: 4.8,
      ageRating: "TV-PG",
      director: "Jon Favreau",
      cast: ["Pedro Pascal", "Katee Sackhoff", "Carl Weathers"],
      tags: ["sci-fi", "space", "western", "star-wars"],
      isNew: false,
      isTrending: true,
      isFeatured: true
    },
    {
      id: "vid_011_squid_game",
      title: "Squid Game",
      thumbnail: "https://images.unsplash.com/photo-1533094602577-198d3beab8ea?w=800&q=80",
      duration: "1h 10m",
      views: "142.7M",
      category: "Survival Drama",
      description: "Hundreds of cash-strapped contestants accept an invitation to compete in children's games for a tempting prize.",
      releaseDate: "2021-09-17",
      rating: 4.6,
      ageRating: "TV-MA",
      director: "Hwang Dong-hyuk",
      cast: ["Lee Jung-jae", "Park Hae-soo", "Wi Ha-jun"],
      tags: ["survival", "thriller", "korean", "drama"],
      isNew: false,
      isTrending: true,
      isFeatured: true
    },
    {
      id: "vid_012_succession",
      title: "Succession: Final Chapter",
      thumbnail: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
      duration: "1h 20m",
      views: "15.8M",
      category: "Drama",
      description: "The Roy family is known for controlling the biggest media and entertainment company in the world.",
      releaseDate: "2023-05-28",
      rating: 4.7,
      ageRating: "TV-MA",
      director: "Jesse Armstrong",
      cast: ["Brian Cox", "Jeremy Strong", "Sarah Snook"],
      tags: ["drama", "family", "business", "power"],
      isNew: false,
      isTrending: false,
      isFeatured: false
    },
    {
      id: "vid_013_house_of_dragon",
      title: "House of the Dragon",
      thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80",
      duration: "1h 15m",
      views: "52.1M",
      category: "Fantasy Epic",
      description: "An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys.",
      releaseDate: "2022-08-21",
      rating: 4.5,
      ageRating: "TV-MA",
      director: "Ryan Condal",
      cast: ["Paddy Considine", "Matt Smith", "Emma D'Arcy"],
      tags: ["fantasy", "epic", "dragons", "medieval"],
      isNew: true,
      isTrending: true,
      isFeatured: true
    },
    {
      id: "vid_014_the_bear",
      title: "The Bear: Season 2",
      thumbnail: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
      duration: "35m",
      views: "21.6M",
      category: "Culinary Drama",
      description: "A young chef from the fine dining world returns to Chicago to run his family's sandwich shop.",
      releaseDate: "2023-06-22",
      rating: 4.8,
      ageRating: "TV-MA",
      director: "Christopher Storer",
      cast: ["Jeremy Allen White", "Ebon Moss-Bachrach", "Ayo Edebiri"],
      tags: ["drama", "cooking", "family", "restaurant"],
      isNew: true,
      isTrending: true,
      isFeatured: false
    },
    {
      id: "vid_015_black_mirror",
      title: "Black Mirror: Beyond",
      thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80",
      duration: "1h 5m",
      views: "38.9M",
      category: "Sci-Fi Anthology",
      description: "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations clash with darkest instincts.",
      releaseDate: "2023-06-15",
      rating: 4.4,
      ageRating: "TV-MA",
      director: "Charlie Brooker",
      tags: ["sci-fi", "anthology", "technology", "dystopian"],
      isNew: true,
      isTrending: false,
      isFeatured: false
    },
    {
      id: "vid_016_the_office",
      title: "The Office: Complete Series",
      thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
      duration: "25m",
      views: "156.2M",
      category: "Comedy",
      description: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes and inappropriate behavior.",
      releaseDate: "2005-03-24",
      rating: 4.8,
      ageRating: "TV-14",
      director: "Greg Daniels",
      cast: ["Steve Carell", "Rainn Wilson", "John Krasinski"],
      tags: ["comedy", "sitcom", "workplace", "mockumentary"],
      isNew: false,
      isTrending: true,
      isFeatured: false
    },
    {
      id: "vid_017_ozark",
      title: "Ozark",
      thumbnail: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      duration: "1h 5m",
      views: "44.7M",
      category: "Crime Thriller",
      description: "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.",
      releaseDate: "2017-07-21",
      rating: 4.6,
      ageRating: "TV-MA",
      director: "Bill Dubuque",
      cast: ["Jason Bateman", "Laura Linney", "Sofia Hublitz"],
      tags: ["crime", "thriller", "money-laundering", "family"],
      isNew: false,
      isTrending: false,
      isFeatured: false
    },
    {
      id: "vid_018_narcos_mexico",
      title: "Narcos: Mexico",
      thumbnail: "https://images.unsplash.com/photo-1531058020387-3be344556be6?w=800&q=80",
      duration: "55m",
      views: "31.4M",
      category: "Crime Drama",
      description: "The rise of the Guadalajara Cartel as an American DEA agent learns the danger of targeting narcos in Mexico.",
      releaseDate: "2018-11-16",
      rating: 4.5,
      ageRating: "TV-MA",
      director: "Carlo Bernard",
      cast: ["Diego Luna", "Michael Peña", "Scoot McNairy"],
      tags: ["crime", "drama", "drugs", "mexico"],
      isNew: false,
      isTrending: false,
      isFeatured: false
    },
    {
      id: "vid_019_night_manager",
      title: "The Night Manager",
      thumbnail: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800&q=80",
      duration: "1h 0m",
      views: "18.3M",
      category: "Spy Thriller",
      description: "A former British soldier is recruited by intelligence to infiltrate an arms dealer's inner circle.",
      releaseDate: "2016-02-21",
      rating: 4.7,
      ageRating: "TV-MA",
      director: "Susanne Bier",
      cast: ["Tom Hiddleston", "Hugh Laurie", "Olivia Colman"],
      tags: ["spy", "thriller", "espionage", "british"],
      isNew: false,
      isTrending: false,
      isFeatured: false
    },
    {
      id: "vid_020_sherlock",
      title: "Sherlock: Modern Cases",
      thumbnail: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=800&q=80",
      duration: "1h 30m",
      views: "73.5M",
      category: "Mystery",
      description: "A modern update finds the famous detective and his doctor partner solving crime in 21st century London.",
      releaseDate: "2010-07-25",
      rating: 4.9,
      ageRating: "TV-14",
      director: "Mark Gatiss",
      cast: ["Benedict Cumberbatch", "Martin Freeman", "Una Stubbs"],
      tags: ["mystery", "detective", "british", "modern"],
      isNew: false,
      isTrending: true,
      isFeatured: true
    },
    {
      id: "vid_021_chernobyl",
      title: "Chernobyl",
      thumbnail: "https://images.unsplash.com/photo-1473186578172-c141e6798cf4?w=800&q=80",
      duration: "1h 10m",
      views: "62.8M",
      category: "Historical Drama",
      description: "In April 1986, an explosion at the Chernobyl nuclear power plant became one of the world's worst man-made catastrophes.",
      releaseDate: "2019-05-06",
      rating: 4.9,
      ageRating: "TV-MA",
      director: "Craig Mazin",
      cast: ["Jared Harris", "Stellan Skarsgård", "Emily Watson"],
      tags: ["historical", "drama", "disaster", "nuclear"],
      isNew: false,
      isTrending: false,
      isFeatured: true
    },
    {
      id: "vid_022_true_detective",
      title: "True Detective: Night Country",
      thumbnail: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80",
      duration: "1h 15m",
      views: "27.9M",
      category: "Crime Mystery",
      description: "When the long winter night falls in Ennis, Alaska, the eight men operating the Tsalal Arctic Research Station vanish.",
      releaseDate: "2024-01-14",
      rating: 4.3,
      ageRating: "TV-MA",
      director: "Issa López",
      cast: ["Jodie Foster", "Kali Reis", "Fiona Shaw"],
      tags: ["crime", "mystery", "detective", "alaska"],
      isNew: true,
      isTrending: true,
      isFeatured: false
    },
    {
      id: "vid_023_queens_gambit",
      title: "The Queen's Gambit",
      thumbnail: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&q=80",
      duration: "1h 0m",
      views: "83.4M",
      category: "Period Drama",
      description: "Orphaned at age nine, Beth develops an amazing talent for chess and pursues her goal to become the world's greatest player.",
      releaseDate: "2020-10-23",
      rating: 4.8,
      ageRating: "TV-MA",
      director: "Scott Frank",
      cast: ["Anya Taylor-Joy", "Bill Camp", "Marielle Heller"],
      tags: ["period", "drama", "chess", "coming-of-age"],
      isNew: false,
      isTrending: false,
      isFeatured: true
    },
    {
      id: "vid_024_arcane",
      title: "Arcane",
      thumbnail: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80",
      duration: "45m",
      views: "58.7M",
      category: "Animated Action",
      description: "Set in utopian Piltover and oppressed Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart.",
      releaseDate: "2021-11-06",
      rating: 4.9,
      ageRating: "TV-14",
      director: "Christian Linke",
      cast: ["Hailee Steinfeld", "Ella Purnell", "Kevin Alejandro"],
      tags: ["animated", "action", "fantasy", "steampunk"],
      isNew: true,
      isTrending: true,
      isFeatured: true
    },
  ]

  return (
    <div className="w-full max-w-screen-4xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="space-y-6">
        <h2 className="text-2xl font-bold">Browse Videos</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 sm:gap-6">
          {videos.map((video) => (
            <VideoCard key={video.id} {...video} />
          ))}
        </div>
      </div>
    </div>
  )
}

export default VideoGrid