"""add/update video processing fields

Revision ID: 2944b960c15e
Revises: c8a105f8d90a
Create Date: 2025-12-13 21:31:01.445780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2944b960c15e'
down_revision: Union[str, Sequence[str], None] = 'c8a105f8d90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('raw_video_path', sa.String(length=500), nullable=False))
    op.add_column('videos', sa.Column('processing_status', sa.String(length=30), nullable=True))
    op.add_column('videos', sa.Column('processing_metadata', sa.JSON(), nullable=True))
    op.add_column('videos', sa.Column('processing_error', sa.String(length=1000), nullable=True))
    op.add_column('videos', sa.Column('manifest_url', sa.String(length=500), nullable=True))
    op.add_column('videos', sa.Column('available_qualities', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_videos_processing_status'), 'videos', ['processing_status'], unique=False)
    op.drop_column('videos', 'video_url')
    op.drop_column('videos', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_videos_processing_status'), table_name='videos')
    op.drop_column('videos', 'available_qualities')
    op.drop_column('videos', 'manifest_url')
    op.drop_column('videos', 'processing_error')
    op.drop_column('videos', 'processing_metadata')
    op.drop_column('videos', 'processing_status')
    op.drop_column('videos', 'raw_video_path')
    # ### end Alembic commands ###
