"""add celery_task_id to video table

Revision ID: 4838fc1c2ea9
Revises: 2944b960c15e
Create Date: 2025-12-20 16:30:23.667317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4838fc1c2ea9'
down_revision: Union[str, Sequence[str], None] = '2944b960c15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('celery_task_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_videos_celery_task_id'), 'videos', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_celery_task_id'), table_name='videos')
    op.drop_column('videos', 'celery_task_id')
    # ### end Alembic commands ###
