"""add storyboard_url to video table

Revision ID: bdc80bbbc0c9
Revises: 4933c49d2a23
Create Date: 2026-07-19 17:33:34.850333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc80bbbc0c9'
down_revision: Union[str, Sequence[str], None] = '4933c49d2a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('storyboard_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'storyboard_url')
    # ### end Alembic commands ###
